---

managed_vms: >-
  {%- set _managed_vms = [] -%}
  {%- for _vm in vm_configs | default([]) -%}
  {%-   set _mgmt_nics = _vm.nics | selectattr('nettype', 'eq', 'network')
                                  | selectattr('netdev', 'eq',
                                               vm_mgmt_net |
                                               default(vm_defaults.network))
                                  | list -%}
  {%-   set _br_nics = _vm.nics | selectattr('nettype', 'eq', 'bridge')
                                  | selectattr('name', 'eq',
                                               vm_external_net |
                                               default(vm_defaults.external))
                                  | list -%}
  {%-   if _mgmt_nics | length -%}
  {%-     set _mgmt_nic = _mgmt_nics | first -%}
  {%-     set _ = _managed_vms.append({'name': _vm.name,
                                       'ip': _mgmt_nic.ip }) -%}
  {%-   elif _br_nics | length -%}
  {%-     set _br_nic = _br_nics | first -%}
  {%-     if _br_nic.addr is defined -%}
  {%-       set _ = _managed_vms.append({'name': _vm.name,
                                         'ip': _br_nic.addr | ansible.utils.ipaddr('address') }) -%}
  {%-     endif -%}
  {%-   endif -%}
  {%- endfor -%}
  {{- _managed_vms -}}
