---

- name: Cleanup existing VNet {{ vnet_config.name }}
  ansible.builtin.include_tasks: cleanup_vnet.yml

- name: Define VNet {{ vnet_config.name }}
  community.libvirt.virt_net:
    command: define
    name: "{{ vnet_config.name }}"
    xml: "{{ lookup('template', 'virt_net.xml.j2') }}"
    autostart: true

- name: Create DHCP reservications for VNet {{ vnet_config.name }}
  when:
    - (vnet_config.dhcp | default(false)) | bool
  block:
    - name: Determine DHCP reservations for VNet {{ vnet_config.name }}
      ansible.builtin.set_fact:
        dhcp_reservations: >-
          {%- set _rsvs = [] -%}
          {%- for _vm in vm_configs -%}
          {%-   for _n in _vm.nics | selectattr('nettype', 'eq', 'network') | selectattr('netdev', 'eq', vnet_config.name) -%}
          {%-     set _ = _rsvs.append(dict(name=_vm.name, mac=_n.mac, ip=_n.ip)) -%}
          {%-   endfor -%}
          {%- endfor -%}
          {{- _rsvs -}}

    - name: Add DHCP reservations for VNet {{ vnet_config.name }}
      community.libvirt.virt_net:
        command: modify
        name: "{{ vnet_config.name }}"
        xml: "<host mac='{{ item.mac }}' name='{{ item.name }}' ip='{{ item.ip }}'/>"
      loop: "{{ dhcp_reservations }}"

- name: Start VNet {{ vnet_config.name }}
  community.libvirt.virt_net:
    command: create
    name: "{{ vnet_config.name }}"
