---

- name: Generate SSH config for VMs
  ansible.builtin.template:
    dest: "{{ [setup_ssh_key.path.local, setup_ssh_key.config.file] | join('/') }}"
    src: "ssh_config.j2"
    mode: "{{ setup_ssh_key.config.mode }}"
