---

- name: Check configuation settings are setup and appropriate
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Check that required settings files are present
      ansible.builtin.stat:
        path: "{{ [playbook_dir | dirname, 'settings', item] | join('/') }}"
      loop: "{{ required_settings }}"
      register: stat_required_settings

    - name: Initialise required settings files if not found
      ansible.builtin.copy:
        src: "{{ [playbook_dir | dirname, 'settings', item.item] | join('/') }}.example"
        dest: "{{ [playbook_dir | dirname, 'settings', item.item] | join('/') }}"
        mode: "0644"
      loop: "{{ stat_required_settings.results }}"
      loop_control:
        label: "{{ item.item }}"
      when:
        - not item.stat.exists
      register: copy_required_settings

    - name: Complain if required settings files were created  # noqa no-handler
      ansible.builtin.assert:
        that:
          - copy_required_settings is not changed
        fail_msg: >-
          Required settings files have been setup.
          Please customise as needed and re-run this playbook to avail of
          these changes.
        quiet: true

    - name: Verify vm_configs has been defined
      ansible.builtin.assert:
        that:
          - vm_configs is defined
        fail_msg: >-
          No 'vm_configs' settings detected.
          Did you copy settings/vms.yml.example to settings/vms.yml and
          customise it?
        quiet: true

    - name: Verify vnet_configs has been defined
      ansible.builtin.assert:
        that:
          - vnet_configs is defined
        fail_msg: >-
          No 'vnet_configs' settings detected.
          Did you copy settings/vnets.yml.example to settings/vnets.yml and
          customise it?
        quiet: true
