---

- name: Ensure libvirt_host is defined
  import_playbook: define_libvirt_host.yml

- name: Ensure specified Ubuntu image is downloaded
  hosts: libvirt_host
  gather_facts: false
  roles:
    - get_ubuntu_image
