---

- name: Ensure libvirt_host is defined
  import_playbook: define_libvirt_host.yml

- name: Ensure libvirt_host ready to host VMs
  hosts: libvirt_host
  tasks:
    - name: Setup libvirt servies
      ansible.builtin.include_role:
        name: libvirt_host
        tasks_from: setup.yml
