---

- name: Ensure active_vms group is defined
  import_playbook: define_active_vms_group.yml

- name: Install required packages on active VMs
  hosts: active_vms
  gather_facts: false
  tasks:

    - name: Determine set of required packages
      ansible.builtin.set_fact:
        required_packages: >-
          {%- set _req_pkgs = [] -%}
          {%- set _pkgs = vm_packages | default(vm_defaults.packages) -%}
          {%- if _pkgs.required is defined -%}
          {%-   set _ = _req_pkgs.extend(_pkgs.required) -%}
          {%- endif -%}
          {{- _req_pkgs -}}

    - name: Update package cache Apt
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      register: update_package_cache
      until: >-
        "Unable to acquire the dpkg frontend lock" is not in (
          update_package_cache.msg | default(''))
      delay: 3
      retries: 5
      when: "'ubuntu' in vm_images_url"

    - name: Register with SUSEConnect
      become: true
      register: suse_connect
      ansible.builtin.command: "/usr/bin/suseconnect -r {{ suseconnect.reg_code }} -e {{ suseconnect.email }} --url {{ suseconnect.url }}"
      until: suse_connect is success
      delay: 10
      retries: 5
      when: >
         suseconnect is defined and
         suseconnect and
         'SLES15-SP' in vm_images_url

    - name: Install required packages Zypper
      become: true
      community.general.zypper:
        name: "{{ required_packages }}"
        state: present
        update_cache: true
        disable_recommends: false
      register: install_required_packages_suse
      until:  install_required_packages_suse is success
      delay: 30
      retries: 10
      when: "'suse' in vm_images_url"


    - name: Install required graphics pattern Zypper
      become: true
      register: install_required_pattern_suse
      ansible.builtin.command: "zypper in --recommends -y -l --type pattern {{ vm_graphics }}"
      until:  install_required_pattern_suse is success
      delay: 10
      retries: 20
      when: >
         "'suse' in vm_images_url" and
         vm_graphics is defined and
         vm_graphics

    - name: set graphics mode
      become: true
      ansible.builtin.command: "systemctl set-default graphical.target"
      delay: 10
      retries: 20
      when: >
         "'suse' in vm_images_url" and
         vm_graphics is defined and
         vm_graphics

    - name: Install required packages Apt
      become: true
      ansible.builtin.apt:
        name: "{{ required_packages }}"
        state: present
      register: install_required_packages
      until: >-
        "Unable to acquire the dpkg frontend lock" is not in (
          install_required_packages.msg | default(''))
      delay: 3
      retries: 5
      when: "'ubuntu' in vm_images_url"

    - name: Upgrade system packages Apt
      become: true
      ansible.builtin.apt:
        upgrade: dist
      register: upgrade_system_packages
      until: >-
        "Unable to acquire the dpkg frontend lock" is not in (
          upgrade_system_packages.msg | default(''))
      delay: 3
      retries: 5
      when: "'ubuntu' in vm_images_url"

    - name: Reboot if required  # noqa no-handler
      become: true
      ansible.builtin.reboot:
      when: >
        (install_required_packages is changed) or
        (upgrade_system_packages is changed) or
        (install_required_packages_suse is changed) or
        (install_required_pattern_suse is changed)
